INSERT INTO STUDENT (STUDENTHAWKID, SEMESTERBUDGET, COURSEID, ACADEMICYEAR) VALUES ('pmarkmann', '20', '1020', 'Senior');
INSERT INTO STUDENT (STUDENTHAWKID, SEMESTERBUDGET, COURSEID, ACADEMICYEAR) VALUES ('bzaputil', '15', '1110', 'Senior');
INSERT INTO STUDENT (STUDENTHAWKID, SEMESTERBUDGET, COURSEID, ACADEMICYEAR) VALUES ('amorris', '18', '1210', 'Senior');
