-- Enter User Data
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("admin1","$2a$12$NVpl06l8ry6h7Nzg5QY4oefEpONxM0JzQ8iocYRHr7MGgx4Qo453m","patrick","markmann",FALSE,"a","bzaputil@gmail.com","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("amorris","$2a$12$f0OVrB1FgcZa2KAsYrQDtO/9derPxF1PWa1NBac6uMVPb0I6rJjjy","Abby","Morris",FALSE,"s","amorris@uiowa.edu","2147483647");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("arangel","$2a$12$H9p9GGsVYZlBjRTWRO1T3OiIF6P7WLy25BmGEJgP.duZZEEQE2VBi","Andres","Rangel",FALSE,"s","arangel@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("student","$2a$12$NVpl06l8ry6h7Nzg5QY4oefEpONxM0JzQ8iocYRHr7MGgx4Qo453m","patrick","markmann",FALSE,"a","bzaputil@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("asegre","$2a$12$oR2GHR2wxy.6.H40w6bjrOHrUkb65AK9VZSE9JLFQZQ08M66YeLra","Alberto","Segre",FALSE,"p","asegre@uiowa.edu","2147483647");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("awolmutt","$2a$12$Z/G21iBWMN.2YbRlfwfK0.l/ovJ0PgLDfuX3uBtGquH/pvfD2ulCS","Aaron","Wolmutt",FALSE,"s","awolmut@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("bzaputil","$2a$12$WTQKpzk9NNoPL3OQ2OLZQejTANnYIvxP2.nPWZ5/dTXSh7n1IB.JO","Bailey","Zaputil",FALSE,"s","bzaputil@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("cgitzlaff","$2a$12$AbhjkoK3JWPccbJ/vm1A/urMuJmSYPCsQdbACt4oi2QRhDUqtS3AW","Cameron","Gitzlaff",FALSE,"s","cgitzlaff@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("cmurphy","$2a$12$byQUkQaODmGpxqvX9JKQuuvf5CfwoADIUj8Dcdm1zH7No6qZGHs9e","Conlan","Murphy",FALSE,"s","cmurphy@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("jdubois","$2a$12$UDRYyUcQmAdTK9x6fA/RpuMIJyrDW.3jkxCjTYhrteFypb3BvMWTO","Johnatan","Bubois",FALSE,"s","jdubois@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("jphourcade","$2a$12$52qSS50xhGmVgjFAmIT5Z.9oJmPr7mkxCofHWnZwxxGo2u3K1EAq.","Juan Pablo","Hourcade",FALSE,"p","jphourcade@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("kbillings","$2a$12$cJSorILPYFIRyRtOfjN44OqMm.hWQ0SrQd.uprpM7bEVl73kr2S.C","Kaisha","Billings",FALSE,"s","kbillings@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("kenokian","$2a$12$juu7OlmQ/hzXLyUEF9HVb.tZtyjmD1CFBAEF.1J2gdhCHkWreGN/6","Ken","Enokian",FALSE,"s","kenokian@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("klang","$2a$12$JTMklbsMD12vmePsPAcLv.JPzZGaeY.QXgHehwrIhlnq3ckdLQSyq","Kyler","Lang",FALSE,"s","klang@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("kmerschman","$2a$12$McsSPqAz8UD6fgpGgJQsrevamaNpaoPVar3rnQ7de0PWHNXxGss5a","Keaton","Merschman",FALSE,"s","kmerschman@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("lbecker","$2a$12$YraRDCiTfJNEppF0Oa5p7.MwO844vgr45xRwjDdJlnSZX2lq8O/bi","Leah","Becker",FALSE,"s","lbecker@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("lpollard","$2a$12$/IhdLQzVEMIDSLlWUsERzuGwcx5CeLmNFf6/qxbqv8tn9QPYOlMHG","Lillian","Pollard",FALSE,"s","lpollard@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("mmarkopoul","$2a$12$3VLhx0.oXAVH1E.WBLik5ORo2VoAVSmI0iAl8ONqP0Pj0Q5FsGUDS","Michael","Markopoulos",FALSE,"s","mmarkpoul@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("npranger","$2a$12$ZROn1lb061j.tXYNhJc3cuklUiWCLGM2h6xBDUc4fWosrUgLcny62","Nathan","Pranger",FALSE,"s","npranger@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("onauman","$2a$12$xIS0CVaWHVvIDaM//zccZeHrl27dA.XMl5LprEy64fYZcpisHPTo.","Olivia","Nauman",FALSE,"s","onauman@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("pmarkmann","$2a$12$xIS0CVaWHVvIDaM//zccZeHrl27dA.XMl5LprEy64fYZcpisHPTo.","Patrick","Markmann",FALSE,"s","pmarkmann@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("ppatel","$2a$12$Nt/JlJI/PYyLhURTUVAy9ObfoGn7NTBVyjgeo6VuUU0yXnpPQ5LuS","Pranav","Patel",FALSE,"s","ppatel@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("rbartlett","$2a$12$66urSA4zvERTcwbAIVkcQut3VGy6ab.L0SgQM38NVJR1qG9MA6hIq","Rachel","Bartlett",FALSE,"s","rbartlett@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("smartinez","$2a$12$BXjWrkRDE/5a/duc1/2G5OCVomy9QbH252rocD/hOxjaFItaVhJ/q","Samantha","Martinez",FALSE,"s","smartinez@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("sniebuhr","$2a$12$l/fVTszjA0NM3bruemzpv.rPVRGnBR6i71iAwtb8.XNubdkKaXFOy","Shelby","Niebuhr",FALSE,"s","sniebuhr@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("tmesserly","$2a$12$9sB6v6Lz7iBbGuNd/7I.4u/3Et2/XTb6fD1qz25NResxQ2DM7M5xi","Tram","Messerly",FALSE,"s","tmesserly@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("krueger","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Zach","Krueger",FALSE,"s","zkrueger@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("bjohnson","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Bob","Johnson",FALSE,"t","bjohnson@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("jjackson","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Jack","Jackson",FALSE,"t","jjackson@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("bsmith","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Betty","Smith",FALSE,"t","bsmith@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("jsullivan","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Janet","Sullivan",FALSE,"t","jsullivan@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("jblue","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Jessica","Blue",FALSE,"t","jblue@uiowa.edu","3425679087");
INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ("krector","$2a$12$A2yPbeL5su./Hwq.1vk0d.NbRTFUImMqWjzkUP7aOBLMZjvY5mI9W","Kyle","Rector",FALSE,"p","krector@uiowa.edu","3425679087");






-- Enter Course Data
INSERT INTO COURSE (COURSEID, STUDENTHAWKID, TUTORHAWKID, PROFESSORHAWKID) VALUES (00001020, "pmarkmann", "bjohnson", "krector");
                                                                                                                                                                                                       
-- Enter Student Data
INSERT INTO STUDENT (STUDENTHAWKID, COURSEID, SEMESTERBUDGET) VALUES ("pmarkmann", 00001020, 15);

-- Enter Tutor Data
INSERT INTO TUTOR (TUTORHAWKID, COURSEID, HOURSPERWEEK) VALUES ("bjohnson", "00001020", "20");

-- Enter Professor Data
INSERT INTO PROFESSOR (PROFESSORHAWKID, COURSEID) VALUES ("krector", "00001020");

-- Enter Slots Data
-- INSERT INTO SLOTS (SLOTID, SLOTDATE, SLOTSTART, SLOTEND, TUTORHAWKID, COURSEID, LOCATION) VALUES ("123456", "4/21", 2:30, 3:00, "bjohnson", "00001020", "Library");

-- Enter Problems Data
-- INSERT INTO PROBLEMS (PROBLEMSETID, PROBLEMSETNAME, PROBLEMSETDESC, PROBLEMFILE, COURSEID) VALUES ("problemid", "problemname", "problemdesc", "problemfile", "courseid");
