-- CODE TO CREATE SQL

DROP TABLE IF EXISTS SESSIONTABLE;
DROP TABLE IF EXISTS PROBLEMs;
DROP TABLE IF EXISTS AVAILABLESLOTS;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS TUTOR;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS USERTABLE;


CREATE TABLE USERTABLE (  -- USER IS A PREDEFINED TERM
	HAWKID VARCHAR(10) NOT NULL,
	HASHED_PSSWRD VARCHAR(255) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	ISADMIN BIT NOT NULL,
	USERROLE VARCHAR(1) NOT NULL,
	EMAIL VARCHAR(255),
	PHONE INT,
	PRIMARY KEY (HAWKID)
	); 
	
CREATE TABLE STUDENT (
	STUDENTHAWKID VARCHAR(10) NOT NULL,
	SEMESTERBUDGET INT(10) NOT NULL,
	COURSEID INT(10) NOT NULL, -- IS THIS AN INTEGER OR A STRING?
	ACADEMICYEAR VARCHAR(255),
	PRIMARY KEY (STUDENTHAWKID),
	FOREIGN KEY (STUDENTHAWKID) REFERENCES USERTABLE(HAWKID)
	
	);
	
CREATE TABLE TUTOR (
	TUTORHAWKID VARCHAR(10) NOT NULL,
	HOURSPERWEEK INT NOT NULL,
	PRIMARY KEY (TUTORHAWKID),
	FOREIGN KEY (TUTORHAWKID) REFERENCES USERTABLE(HAWKID)
	
	);
	
-- NO PROFESSOR TABLE AS HE TOLD US TO GET RID OF IT.

CREATE TABLE COURSE (
	COURSEID INT NOT NULL,
	STUDENTHAWKID VARCHAR(10) NOT NULL, -- PUT THIS ON HERE SEVERAL TIMES? ONE FOR EACH PERSON?
	TUTORHAWKID VARCHAR(10) NOT NULL,
	PROFESSORHAWKID VARCHAR(10) NOT NULL,
	PRIMARY KEY (COURSEID),
	FOREIGN KEY (PROFESSORHAWKID ) REFERENCES USERTABLE(HAWKID),
	FOREIGN KEY (STUDENTHAWKID) REFERENCES STUDENT (STUDENTHAWKID),
	FOREIGN KEY (TUTORHAWKID) REFERENCES TUTOR (TUTORHAWKID)
	);
	
	
CREATE TABLE AVAILABLESLOTS (
	SLOTID INT NOT NULL AUTO_INCREMENT,
	DATEANDTIME DATETIME NOT NULL,
	TUTORHAWKID VARCHAR(10) NOT NULL,
	PRIMARY KEY (SLOTID),
	FOREIGN KEY (TUTORHAWKID) REFERENCES TUTOR (TUTORHAWKID)
	
	);

	
CREATE TABLE PROBLEMS (
	PROBLEMSETID INT NOT NULL AUTO_INCREMENT,
	PROBLEMSETNAME VARCHAR(255) NOT NULL,
	COURSEID INT NOT NULL,
	PRIMARY KEY (PROBLEMSETID),
	FOREIGN KEY (COURSEID) REFERENCES COURSE (COURSEID)
	
	);
	
CREATE TABLE SESSIONTABLE (
	SESSIONID INT NOT NULL AUTO_INCREMENT,
	PROBLEMSETID INT NOT NULL,
	STUDENTHAWKID VARCHAR(10) NOT NULL,
	TUTORHAWKID VARCHAR(10) NOT NULL,
	CANCEL BIT,
	LOCATION VARCHAR(255),
	PRIMARY KEY (SESSIONID),
	FOREIGN KEY (STUDENTHAWKID) REFERENCES STUDENT (STUDENTHAWKID),
	FOREIGN KEY (TUTORHAWKID) REFERENCES TUTOR (TUTORHAWKID),
	FOREIGN KEY (PROBLEMSETID) REFERENCES PROBLEMS (PROBLEMSETID)

	);

INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ('pat', '123456', 'patrick', 'markmann', 'T', 'a', 'patrick-markmann@uiowa.edu', '123456789');

INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ('joe', 'joesmith', 'joe', 'smith', 'F', 's', 'joe-smith@uiowa.edu', '987654321');

INSERT INTO USERTABLE (HAWKID, HASHED_PSSWRD, FIRSTNAME, LASTNAME, ISADMIN, USERROLE, EMAIL, PHONE) VALUES ('bob', 'bobjohnson', 'bob', 'johnson', 'F', 't', 'bob-johnson@uiowa.edu', '111222333');


