UPDATE USERTABLE SET FIRSTNAME="Bob", LASTNAME="Belcher",USERROLE='a',EMAIL="'bobbelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="admin1";
UPDATE USERTABLE SET FIRSTNAME="Tina", LASTNAME="Belcher",USERROLE='s',EMAIL="'tinabelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="student1";
UPDATE USERTABLE SET FIRSTNAME="Linda", LASTNAME="Belcher",USERROLE='t',EMAIL="'lindabelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="tutor1";
UPDATE USERTABLE SET FIRSTNAME="Gene", LASTNAME="Belcher",USERROLE='p',EMAIL="'genebelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="teacher1";
