UPDATE USERTABLE SET FIRSTNAME="Bob", LASTNAME="Belcher",ISADMIN=TRUE,USERROLE='a',EMAIL="'bobbelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="admin1";
UPDATE USERTABLE SET FIRSTNAME="Tina", LASTNAME="Belcher",ISADMIN=FALSE,USERROLE='s',EMAIL="'tinabelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="student1";
UPDATE USERTABLE SET FIRSTNAME="Linda", LASTNAME="Belcher",ISADMIN=FALSE,USERROLE='t',EMAIL="'lindabelcher@gmail.com",PHONE=3193898008 WHERE HAWKID="tutor1";

